"""Ninth migration

Revision ID: 19b6c9189c5d
Revises: 46443eebaa82
Create Date: 2024-10-03 20:58:51.874172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b6c9189c5d'
down_revision: Union[str, None] = '46443eebaa82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
