"""Eleventh migration

Revision ID: f0896022decc
Revises: c044ac7ad9e4
Create Date: 2024-10-11 12:12:31.944974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0896022decc'
down_revision: Union[str, None] = 'c044ac7ad9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_messages', schema=None) as batch_op:
        batch_op.alter_column('user_message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ai_response_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_messages', schema=None) as batch_op:
        batch_op.alter_column('ai_response_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_message_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
